### ISSUE TITLE
Warnings in Dev Console when Gauge Chart is rendered

### ISSUE THREAD

**Issue by haidermahmood** [Reggino/react-svg-gauge#1]
Tim,
When I ran the Gauge chart in my chrome, I got warnings in developer console. Please see the warnings in screenshot attached. The React version I am using is 15.2.0

![error](https://cloud.githubusercontent.com/assets/6479402/17859921/e1d96f80-68a4-11e6-98c0-f344b58c1421.PNG)
![error2](https://cloud.githubusercontent.com/assets/6479402/17859922/e1d9fb12-68a4-11e6-8ac5-f24bec0a0b51.PNG)
![error3](https://cloud.githubusercontent.com/assets/6479402/17859923/e1de2296-68a4-11e6-9405-58583a58f4e9.PNG)

Regards,
Haider

**Comment by Reggino** [comment]
Hi Haider,

Just released version 1.0.2. where this is fixed. Thanks for the report.
