### ISSUE TITLE
Can i modify number with text render ? 

### ISSUE THREAD

**Issue by osvaldoalvaradodev** [Reggino/react-svg-gauge#15]
can i modify number with text render ? 

bad , normal, good ? 

For example 

![image](https://user-images.githubusercontent.com/25690921/46474951-8be9cd00-c7ba-11e8-9780-d86a51fc41ce.png)

**Comment by Reggino** [comment]
I've just released version 1.0.10 that allow you to pass a custom `valueRenderer`. This way you can show whatever text you like. 

I'll try and update the example pages @ https://reggino.github.io/react-svg-gauge/ for a demo

**Comment by osvaldoalvaradodev** [comment]
Thanks so much!!!

It's very important this feature! :D
