### ISSUE TITLE
Gradient  Color in Gauge & Position Label

### ISSUE THREAD

**Issue by haidermahmood** [Reggino/react-svg-gauge#2]
Hi,

Please tell if we can change the gauge color to gradient like in attached screenshot
![gvegb](https://cloud.githubusercontent.com/assets/6479402/17860102/a53b59c0-68a5-11e6-89df-3ed58d3bea07.png)

Can we know the position of value so we can position the label at that point?

**Comment by Reggino** [comment]
Hi!

You probably have to fork the component for these things.

Documentation on an SVG gradient can be found here: https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Gradients . Add some extra gradient-settings to the `<defs>` section in the `render`-method, apply that to the path and you should be fine.

The position of the value can be retrieved by looking at the `_getPathValues`-method. When you pass your value, the result `Xo` / `Yo` / `Xi` / `Yi` (X and Y in inner / outer coordinates.). You may want to look at http://justgage.com/examples/pointer.html for inspiration!

**Comment by haidermahmood** [comment]
Tim,

I have made progress after changing the code a bit. Now I can see gradient and get the value coordinates. I can create a fork for that. But is it possible if I use my fork for using in a project? I would like to use your package in my project but customized. I mean I want to add it in package.json. So, what do you think I should do as it is your code originally.

Regards,
Haider

**Comment by Reggino** [comment]
Haider,

Feel free to copy, paste and adjust the source as you need in your own project.

Regards

Tim

**Comment by haidermahmood** [comment]
Thanks, Tim
