### ISSUE TITLE
Change font color of formatter

### ISSUE THREAD

**Issue by osvaldoalvaradodev** [Reggino/react-svg-gauge#21]
Have way to change color in valueFormatter prop?

I change to pass style but only works fontSize and fontFamily.

`       valueLabelStyle ={{
                fontSize:100,
                fontFamily:'Arial',
                color:'blue'

            }}`

![image](https://user-images.githubusercontent.com/25690921/46619762-5108d180-caf9-11e8-8e6f-eea31c2025fb.png)

**Comment by osvaldoalvaradodev** [comment]
i try to change colors of top label style but dont works too.

Only works fontSize.

This is a issue of last version ? 

` topLabelStyle ={{
                backgroundColor: '#00FF00',
                color:'red',
                fontSize:60,
            }}
            valueLabelStyle ={{
                backgroundColor: '#00FF00',
                color:'red',
                fontSize:60,

            }}`

![image](https://user-images.githubusercontent.com/25690921/46621896-23bf2200-caff-11e8-9d43-3e2133f91574.png)

**Comment by hilsaga** [comment]
Since SVG uses "fill" to determine font color but not "color" in classical css.
Please try
valueLabelStyle={{
fontSize:100,
fontFamily:'Arial',
fill:'blue'
}}

**Comment by osvaldoalvaradodev** [comment]
Thanks! i tri and works!!! :)
