### ISSUE TITLE
How to change max label

### ISSUE THREAD

**Issue by proasian42** [Reggino/react-svg-gauge#28]
I want to know if there is a way to change the text of max value like this. I tried to change a max value, but the gauge will disappear if the max is 0. 

I would appreciate it if you have a way to do that. Thanks!

![image](https://user-images.githubusercontent.com/22419545/72270867-d419b100-35f3-11ea-95b6-6db3f8d63e8c.png)

**Comment by Reggino** [comment]
The ```max```-value in the component configuration is not only used to display the text on the right, but also to calculate the filled percentage. There currently is no way to override the max-label with configuration.

You can just copy and paste the component source in your own project and change line 150 of ```src/Gauge.tsx```

**Comment by Reggino** [comment]
Related to issue #22
