### ISSUE TITLE
How to build into lib

### ISSUE THREAD

**Issue by haidermahmood** [Reggino/react-svg-gauge#4]
Tim,

Please see attached image of the gauge. I was able to adjust the width and also add gradiant. However, I was working directly on lib/gauge.js. I have added those changes to src but I am not able to compile into lib. Please tell what command do you use from scripts to make a new lib folder?
![customgauge](https://cloud.githubusercontent.com/assets/6479402/17890644/c0eee956-6950-11e6-9e49-7ea75a0533a0.PNG)

**Comment by haidermahmood** [comment]
By the way, I am using windows 10.

**Comment by Reggino** [comment]
`npm run build` should do the trick!

**Comment by haidermahmood** [comment]
Please see attached screenshot of errors I am getting on npm run build.
![gauge_test](https://cloud.githubusercontent.com/assets/6479402/17891251/0a5c19e4-6954-11e6-9614-605078ecfae6.PNG)

**Comment by Reggino** [comment]
Not sure why, but Windows doesn't run `npm` scripts with `node` by default.

I've adjusted the build script. Please see the new version for an updated package.json / build script. Should work on Windows now.
