### ISSUE TITLE
How to remove "padding" around gauge

### ISSUE THREAD

**Issue by DaddyWarbucks** [Reggino/react-svg-gauge#5]
How would I go about removing the extra whitespace around the gauge?

I am trying to remove the space _around_ the gauge so that the gauge (and min/max number) takes up the full width and height of the SVG.

Whitespace can be seen here:
<img width="1440" alt="screen shot 2017-01-11 at 5 18 04 pm" src="https://cloud.githubusercontent.com/assets/4671808/21870497/4a5111f2-d822-11e6-8bd2-d3dd549d57b4.png">

You can see that the gauge is not centered vertically/horizontally. I have different use cases making the gauge bigger, which seems to alleviate some of the problem. Which can be seen below:
<img width="1440" alt="screen shot 2017-01-11 at 5 23 50 pm" src="https://cloud.githubusercontent.com/assets/4671808/21870622/e46c5ee0-d822-11e6-97de-53a50696cee9.png">

I have tried poking around with the Xo, Xi, Yo, Yi params to no avail. Is there some sort of width/height ratio that could solve this? Such as:
```
gaugeWidth - 100;
gaugeHeight = gaugeWidth * 0.6666667;
```

Ideally, I would like the gauge paths to start/end at the left/right/top/bottom most borders of the overall SVG.

Any help would be greatly appreciated and thanks for the hard work already!

**Comment by Reggino** [comment]
The .svg layout is based on [http://justgage.com/](http://justgage.com/) . Padding is not configurable a.t.m. but you may achieve the desired effect by fiddling with the source at: (`_getPathValues`) . `_getPathValues` generates the anchor-points for the arc-path.

`Cy` is the bottom of the arc. When set to `this.props.height`, the arc should have no bottom padding.
`Cx` is x coordinate of the the center of the arc.
`Ro` is the outer radius of the arc. When the outer radius is set to the same value as `Cx` you should have no more padding on the left side.
etc...

This may give you some clues, but it may require a bit of puzzling to get this set up.

I'ld be happy to review a PR  if you could get something working.!

**Comment by DaddyWarbucks** [comment]
Thanks for the pointers! I will look into this soon

**Comment by hodn** [comment]
Hi, have you found an optimal solution? I am currently using negative margin with the svg component. 
Thanks.

**Comment by DaddyWarbucks** [comment]
@hodn Its been a long time since I have worked with this. I do still have the component in production though, but heavily modified. I actually copy/pasted most of this code and made lots of modifications to make it work for what I needed.  But I don't remember exactly what I did to get the padding correct. I believe it was following the advice given above. Sorry I can't be more help.
