### ISSUE TITLE
Weird behavior when value exceeds limits

### ISSUE THREAD

**Issue by robvenn** [Reggino/react-svg-gauge#7]
If the provided value exceeds the min and max values the gauge renders incorrectly, could possibly be improved by rendering it as completely full or empty, eg. quick fix: `const value = data >= min && data <= max ? data : data < min ? min : max`

**Comment by Reggino** [comment]
Looks great. Could you please send a pull request? Thanks!

**Comment by robvenn** [comment]
Ok, looking into it. At first sight it seems to work on your demo page but I did find this bug in an app that I was working on (didn't write this code myself originally) so will need to check what exactly was going wrong there.

**Comment by robvenn** [comment]
Actually, seems like this was fixed in ca9d218778d81c227bb9cc195b2c09219f23c928 but it was not published to npm with new version. @Reggino can you publish the patch and close this ticket? You can check current files on npm with https://npm.runkit.com/react-svg-gauge/src/Gauge.js?t=1499607450528

**Comment by Reggino** [comment]
Ah... sorry, my bad.

Just published v1.0.5 . Thanks for the reminder!

**Comment by robvenn** [comment]
Cool, thanks, glad to help.
